/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.Koneksi;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Form_DasbordKaryawan extends javax.swing.JPanel {

    PreparedStatement ps;
    ResultSet rs;
    Date tanggal = new Date();

    public Form_DasbordKaryawan() {
        initComponents();
        p_notifikasi.hide();
        loadDashboard();
    }

    private void loadDashboard() {
        totalPenjualan();     
        totalProduk();
        totalPendapatan();
        notifikasi();
        tampilStok();
        tampilTerlaris();
        tampilLaporan();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalBarang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lb_totalPenjualan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lb_totalProduk = new javax.swing.JLabel();
        p_notifikasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_caristok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_stok = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_favorit = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_laporan = new javax.swing.JTable();
        txt_terlaris = new javax.swing.JTextField();
        btn_cariterlaris = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lb_pendapatan = new javax.swing.JLabel();

        totalBarang.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        totalBarang.setForeground(new java.awt.Color(255, 255, 255));
        totalBarang.setText("0");
        totalBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Banyak Barang");

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(210, 218, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Dasboard Karyawan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Penjualan Hari Ini");

        lb_totalPenjualan.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        lb_totalPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_totalPenjualan.setText("0");
        lb_totalPenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_totalPenjualan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lb_totalPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 260, 490, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Produk Dapat Dijual");

        lb_totalProduk.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        lb_totalProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_totalProduk.setText("0");
        lb_totalProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_totalProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_totalProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 500, -1));

        p_notifikasi.setBackground(new java.awt.Color(255, 0, 0));
        p_notifikasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        p_notifikasi.setPreferredSize(new java.awt.Dimension(900, 56));
        p_notifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_notifikasiMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Peringatan!! terdapat stok produk kurang dari 3 buah");

        javax.swing.GroupLayout p_notifikasiLayout = new javax.swing.GroupLayout(p_notifikasi);
        p_notifikasi.setLayout(p_notifikasiLayout);
        p_notifikasiLayout.setHorizontalGroup(
            p_notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_notifikasiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_notifikasiLayout.setVerticalGroup(
            p_notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_notifikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(p_notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 190, 1060, 49));

        txt_stok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_stok.setText("3");
        jPanel1.add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 132, 29));

        jLabel4.setText("stok produk kurang dari :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        btn_caristok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/image/search.png"))); // NOI18N
        btn_caristok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caristokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_caristok, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 26, 29));

        tb_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tb_stok);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 294, 118));

        jLabel5.setText("produk favorit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        tb_favorit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tb_favorit);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 310, 118));

        jLabel6.setText("Penjualan hari ini");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, -1, -1));

        tb_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(tb_laporan);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 318, 153));

        txt_terlaris.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_terlaris.setText("5");
        jPanel1.add(txt_terlaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 41, -1));

        btn_cariterlaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/image/search.png"))); // NOI18N
        btn_cariterlaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariterlarisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cariterlaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 30, 20));

        jLabel11.setText("baris :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 255, 51));
        jPanel5.setMaximumSize(new java.awt.Dimension(899, 87));
        jPanel5.setMinimumSize(new java.awt.Dimension(899, 87));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel12.setText("Total Pendapatan Hari Ini :  Rp");

        lb_pendapatan.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lb_pendapatan.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lb_pendapatan))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 1020, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void p_notifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_notifikasiMouseClicked
        
    }//GEN-LAST:event_p_notifikasiMouseClicked

    private void btn_caristokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caristokActionPerformed
        
    }//GEN-LAST:event_btn_caristokActionPerformed

    private void btn_cariterlarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariterlarisActionPerformed
        
    }//GEN-LAST:event_btn_cariterlarisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caristok;
    private javax.swing.JButton btn_cariterlaris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_pendapatan;
    private javax.swing.JLabel lb_totalPenjualan;
    private javax.swing.JLabel lb_totalProduk;
    private javax.swing.JPanel p_notifikasi;
    private javax.swing.JTable tb_favorit;
    private javax.swing.JTable tb_laporan;
    private javax.swing.JTable tb_stok;
    private javax.swing.JLabel totalBarang;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_terlaris;
    // End of variables declaration//GEN-END:variables

private void totalPenjualan() {
        try {
            String sql = "SELECT total_penjualan FROM view_total_penjualan WHERE tanggal_penjualan = CURRENT_DATE";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()) {
                lb_totalPenjualan.setText(String.valueOf(rs.getInt("total_penjualan")));
            } else {
                lb_totalPenjualan.setText("0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error totalPenjualan(): " + e.getMessage());
        }
    }



    private void totalPendapatan() {
        try {
            String sql = "SELECT total_pendapatan FROM view_total_pendapatan WHERE tanggal_penjualan = CURRENT_DATE";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()) {
                lb_pendapatan.setText(String.valueOf(rs.getInt("total_pendapatan")));
            } else {
                lb_pendapatan.setText("0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error totalPendapatan(): " + e.getMessage());
        }
    }

    private void totalProduk() {
        try {
            String sql = "SELECT total_produk FROM view_total_produk";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()) {
                lb_totalProduk.setText(String.valueOf(rs.getInt("total_produk")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error totalProduk(): " + e.getMessage());
        }
    }

    private void notifikasi() {
        try {
            String sql = "SELECT COUNT(*) AS kurang FROM view_stok_rendah";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next() && rs.getInt("kurang") > 0) {
                p_notifikasi.setVisible(true);
            } else {
                p_notifikasi.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error notifikasi(): " + e.getMessage());
        }
    }

    private void tampilStok() {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{"Kode Produk", "Nama Produk", "Stok"}, 0);
            String sql = "SELECT * FROM view_stok_rendah";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_produk"),
                    rs.getString("nama_produk"),
                    rs.getInt("stok_produk")
                });
            }
            tb_stok.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tampilStok(): " + e.getMessage());
        }
    }

    private void tampilTerlaris() {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{"Kode Produk", "Nama Produk", "Harga Jual"}, 0);
            String sql = "SELECT * FROM view_produk_terlaris";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_produk"),
                    rs.getString("nama_produk"),
                    rs.getInt("harga_jual")
                });
            }
            tb_favorit.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tampilTerlaris(): " + e.getMessage());
        }
    }

    private void tampilLaporan() {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{"Kode Transaksi", "Total Harga", "Kasir"}, 0);
            String sql = "SELECT penjualan_id, total_pembayaran, nama_user FROM view_laporan_harian WHERE tanggal_penjualan = CURRENT_DATE";
            ps = Koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("penjualan_id"),
                    rs.getInt("total_pembayaran"),
                    rs.getString("nama_user")
                });
            }
            tb_laporan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tampilLaporan(): " + e.getMessage());
        }
    }
}

